// Generates the brush ensō paths in src/components/ui/enso-paths.ts.
//
//   node scripts/generate-enso.mjs
//
// The shape is a sumi-ink ensō: it lands heavy, swells through the bottom,
// lifts along the top and (in the large version) splits into dry bristle
// streaks at the tail, leaving the gap at the top right like the logo.
// Output is static path data, so the app ships the shape, not this code.
// It is written in Prettier's layout, so regenerating leaves no format diff.
import { writeFileSync } from "node:fs";

const T0 = -35; // start angle, degrees (0 = 3 o'clock, clockwise)
const SWEEP = 320;
const R = 38; // centre-line radius in a 100×100 box

const rad = (d) => (d * Math.PI) / 180;
const radius = (t) => R + 1.4 * Math.sin(t * Math.PI * 2.1 + 0.4) - 1.2 * t;
// pressure: lands heavy, swells through the bottom, lifts along the top
const width = (t) => {
  const land = 0.7 + 0.3 * Math.sin((Math.min(t / 0.05, 1) * Math.PI) / 2);
  const belly = 1 + 0.28 * Math.exp(-((t - 0.32) ** 2) / 0.02);
  return 12.5 * land * belly * (1 - 0.62 * t);
};
// paper drag: a little high-frequency roughness on each edge
const rough = (t, k) =>
  0.26 * Math.sin(t * 91 + k) +
  0.16 * Math.sin(t * 217 + 2 * k) +
  0.08 * Math.sin(t * 431 + 3 * k);
const smooth = (a, b, x) => {
  const k = Math.min(1, Math.max(0, (x - a) / (b - a)));
  return k * k * (3 - 2 * k);
};
const pt = (t, off) => {
  const a = rad(T0 + t * SWEEP);
  const r = radius(t) + off;
  return [50 + r * Math.cos(a), 50 + r * Math.sin(a)];
};

/** One filled ribbon along the arc, written with relative moves. */
function ribbon(t0, t1, offOf, wOf, { steps, head = false, roughen = true }) {
  const out = [];
  const inn = [];
  for (let i = 0; i <= steps; i++) {
    const t = t0 + ((t1 - t0) * i) / steps;
    const o = offOf(t);
    const w = wOf(t) / 2;
    const k = roughen ? Math.min(1, w) : 0;
    out.push(pt(t, o + w + rough(t, 1) * k));
    inn.push(pt(t, o - w + rough(t, 5) * k));
  }
  const pts = [...out, ...inn.reverse()];
  if (head) {
    // rounded landing blob behind the start point
    const a0 = rad(T0);
    const w0 = wOf(t0) / 2;
    const c = pt(t0, offOf(t0));
    const nx = Math.cos(a0);
    const ny = Math.sin(a0);
    const tx = Math.sin(a0);
    const ty = -Math.cos(a0);
    for (let i = 1; i < 10; i++) {
      const q = (Math.PI * i) / 10;
      pts.push([
        c[0] - nx * w0 * Math.cos(q) + tx * w0 * 1.08 * Math.sin(q),
        c[1] - ny * w0 * Math.cos(q) + ty * w0 * 1.08 * Math.sin(q),
      ]);
    }
  }
  const r1 = (v) => {
    const s = (Math.round(v * 10) / 10).toString();
    return s.replace(/^0\./, ".").replace(/^-0\./, "-.");
  };
  let d = `M${r1(pts[0][0])} ${r1(pts[0][1])}`;
  let [px, py] = [
    Math.round(pts[0][0] * 10) / 10,
    Math.round(pts[0][1] * 10) / 10,
  ];
  for (const [x, y] of pts.slice(1)) {
    const rx = Math.round(x * 10) / 10;
    const ry = Math.round(y * 10) / 10;
    const dx = r1(rx - px);
    const dy = r1(ry - py);
    d += `l${dx}${dy.startsWith("-") ? "" : " "}${dy}`;
    px = rx;
    py = ry;
  }
  return d + "z";
}

function brush() {
  let d = ribbon(
    0,
    0.7,
    () => 0,
    (t) => width(t) * (1 - smooth(0.52, 0.7, t)),
    {
      steps: 90,
      head: true,
    },
  );
  // [offset across the stroke, start, end, thickness, gap start, gap end]
  const strands = [
    [-0.44, 0.5, 0.83, 0.2, 0.7, 0.73],
    [-0.26, 0.48, 0.96, 0.24, 0, 0],
    [-0.08, 0.5, 1.0, 0.3, 0.86, 0.885],
    [0.1, 0.52, 0.93, 0.22, 0, 0],
    [0.27, 0.5, 0.88, 0.26, 0.76, 0.8],
    [0.45, 0.48, 0.78, 0.18, 0, 0],
  ];
  for (const [o, s0, end, th, g0, g1] of strands) {
    const wOf = (t) =>
      width(t) *
      th *
      (1 - smooth(end - 0.14, end, t)) *
      (0.85 + 0.15 * Math.sin(t * 60 + o * 9));
    const off = (t) => o * width(t) * (1 + 0.5 * smooth(0.6, 1, t));
    const steps = (a, b) => Math.max(8, Math.round((b - a) * 70));
    if (g1 > g0) {
      d += ribbon(s0, g0, off, wOf, { steps: steps(s0, g0) });
      d += ribbon(g1, end, off, wOf, { steps: steps(g1, end) });
    } else {
      d += ribbon(s0, end, off, wOf, { steps: steps(s0, end) });
    }
  }
  return d;
}

// Small sizes (checkboxes, spinners): one tapered ribbon, no streaks or
// roughness, which would only turn to noise at 20px.
const small = () =>
  ribbon(
    0,
    1,
    () => 0,
    (t) => Math.max(0.4, width(t) * 1.55 * (1 - smooth(0.62, 1, t) * 0.9)),
    { steps: 48, head: true, roughen: false },
  );

const file = `// Generated by scripts/generate-enso.mjs. Don't edit by hand.
// viewBox 0 0 100 100. The brush starts at ${T0}° and sweeps ${SWEEP}° clockwise.

/** Large ensō with dry bristle streaks: sign-in, empty day, focus done. */
export const ENSO_BRUSH =
  "${brush()}";

/** Small ensō, one tapered stroke: task checkboxes and spinners. */
export const ENSO_BRUSH_SMALL =
  "${small()}";
`;
writeFileSync(
  new URL("../src/components/ui/enso-paths.ts", import.meta.url),
  file,
);
console.log(`enso-paths.ts: ${file.length} bytes`);
