-- Ensure all necessary columns exist for the new Settings page
ALTER TABLE user_settings
ADD COLUMN IF NOT EXISTS display_name text,
ADD COLUMN IF NOT EXISTS timezone text DEFAULT 'UTC',
ADD COLUMN IF NOT EXISTS avatar_color text DEFAULT '#E5B41E',
ADD COLUMN IF NOT EXISTS theme text DEFAULT 'navy',
ADD COLUMN IF NOT EXISTS color_mode text DEFAULT 'dark',
ADD COLUMN IF NOT EXISTS ambient_bg boolean DEFAULT true,
ADD COLUMN IF NOT EXISTS reduce_motion boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS notifications_enabled boolean DEFAULT true,
ADD COLUMN IF NOT EXISTS quiet_start time DEFAULT '22:00',
ADD COLUMN IF NOT EXISTS quiet_end time DEFAULT '08:00',
ADD COLUMN IF NOT EXISTS daily_briefing boolean DEFAULT true,
ADD COLUMN IF NOT EXISTS pomodoro_sound boolean DEFAULT true,
ADD COLUMN IF NOT EXISTS pomodoro_duration int DEFAULT 25,
ADD COLUMN IF NOT EXISTS short_break_duration int DEFAULT 5,
ADD COLUMN IF NOT EXISTS long_break_duration int DEFAULT 15,
ADD COLUMN IF NOT EXISTS auto_start_breaks boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS default_view text DEFAULT 'list',
ADD COLUMN IF NOT EXISTS auto_archive_days int DEFAULT 7,
ADD COLUMN IF NOT EXISTS do_categories text[] DEFAULT ARRAY['work','study','personal','errand','health'],
ADD COLUMN IF NOT EXISTS auto_snooze boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS smart_routing_enabled boolean DEFAULT true,
ADD COLUMN IF NOT EXISTS nlp_date_parsing boolean DEFAULT true,
ADD COLUMN IF NOT EXISTS routing_confidence text DEFAULT 'Medium',
ADD COLUMN IF NOT EXISTS ollama_enabled boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS ollama_url text DEFAULT 'http://localhost:11434',
ADD COLUMN IF NOT EXISTS location_detection boolean DEFAULT false;
